// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWW5AATJvuMwGitA2jjHZXSTjb3s4tsAA',
    appId: '1:941625134931:web:68cc2e0b2110c25777dba6',
    messagingSenderId: '941625134931',
    projectId: 'collagedash',
    authDomain: 'collagedash.firebaseapp.com',
    storageBucket: 'collagedash.firebasestorage.app',
    measurementId: 'G-FW7D36WXNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBks4HgLT7cX9hybXbNjhm-OA2gygZGDFU',
    appId: '1:941625134931:android:dd7b52282eac860177dba6',
    messagingSenderId: '941625134931',
    projectId: 'collagedash',
    storageBucket: 'collagedash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRH-q_n4VctmxrrnxZ_j9Pwkeks7q-7r4',
    appId: '1:941625134931:ios:2750db45f410f5e277dba6',
    messagingSenderId: '941625134931',
    projectId: 'collagedash',
    storageBucket: 'collagedash.firebasestorage.app',
    iosBundleId: 'com.example.educaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRH-q_n4VctmxrrnxZ_j9Pwkeks7q-7r4',
    appId: '1:941625134931:ios:2750db45f410f5e277dba6',
    messagingSenderId: '941625134931',
    projectId: 'collagedash',
    storageBucket: 'collagedash.firebasestorage.app',
    iosBundleId: 'com.example.educaps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWW5AATJvuMwGitA2jjHZXSTjb3s4tsAA',
    appId: '1:941625134931:web:4db59520b6bc914677dba6',
    messagingSenderId: '941625134931',
    projectId: 'collagedash',
    authDomain: 'collagedash.firebaseapp.com',
    storageBucket: 'collagedash.firebasestorage.app',
    measurementId: 'G-MFGKNT0JD8',
  );
}
